### ISSUE TITLE
agrisemantics.org home page

### ISSUE THREAD

**Issue by catecara** [agrisemantics/website#13]
Semantics for the Interoperability of Agricultural Data

Modern agriculture needs data on a wide range of topics, from crop yields to soil composition and rainfall, in a wide range of digital formats, from spreadsheets to maps. How well such diverse data sources can be integrated to solve specific problems in agriculture depends in part on whether its "meaning" is correctly defined, which allows it to be used in a straightforward manner in different information systems ("semantic interoperability"). 

Much is ongoing in the area of semantic interoperability, in particular for agriculture. Here just a few pointers: 

**International Initiatives**
- The [Agrisemantics WG at RDA](https://www.rd-alliance.org/groups/agrisemantics-wg.html) gathers researchers and practitioners interested in producing and accessing more interoperable data in agriculture. To this end, the WG produced a [set of recommendations to facilitate the use of semantics for data on agriculture and nutrition](url). If you have [comments on the recommendations, you can post them here] (url).

**Standard vocabularies and classifications**  
- A catalog of standards for agriculture is provided by the [Agrisemantics Map of Standards](https://vest.agrisemantics.org/).
- A repository of ontologies: [AgroPortal](http://agroportal.lirmm.fr/)
- The Global Agricultural Concept Space ([GACS](http://browser.agrisemantics.org/gacs/en/))
- Statistical classifications for agriculture as Linked Open Vocabularies [Caliper](http://stats-class.fao.uniroma2.it/caliper/).

**Tools**
- Editing RDF, OWL: [VocBench](http://vocbench.uniroma2.it/)
- Browsing and searching RDF, SKOS: [SKOSMOS](http://skosmos.org/)

**Comment by brandonnodnarb** [comment]
added a few links.  Should be consistent with how things are listed --- e.g. project then discription or the other way around.  

I would add links for RDF, OWL, VocBench, Skosmos, etc.

**Comment by brandonnodnarb** [comment]
I would link to the document/web page for the recommendations, and then add another sentence identifying that's where the discussion is (or will) happen  --- with links to the github issues

**Comment by catecara** [comment]
Added a couple of links. Yes, the recommendations should link to the dedicated page, I would then add the link to github there.

**Comment by brandonnodnarb** [comment]
done.
