### ISSUE TITLE
replace the image with a lighter version

### ISSUE THREAD

**Issue by saubin78** [agrisemantics/website#14]
to slow to display...
I have this very light version
![SEMANTICS-RICE_poster_veryLD](https://user-images.githubusercontent.com/18008698/66815666-f9394d80-ef38-11e9-950b-1e7964ce2e4e.jpg)

Does it work?
Sophie

**Comment by brandonnodnarb** [comment]
I can swap the image.  I've already made multiple edits; can we make this part of the discussion tomorrow?

**Comment by brandonnodnarb** [comment]
Also, it's loading the file from the RDA website, not the local copy, which likely accounts for some of the lag.

**Comment by brandonnodnarb** [comment]
This is fixed in the docs.  Will be resolved with next deploy.

**Comment by brandonnodnarb** [comment]
done.  now on local copy
