### ISSUE TITLE
https://agrisemantics.org/#agsem_about/

### ISSUE THREAD

**Issue by catecara** [agrisemantics/website#16]
Placeholder for Caterina

**Comment by catecara** [comment]
The Agrisemantics Working Group within RDA, the Research Data Alliance, gathers together researchers and practitioners at the crossing point between agriculture and data management. The final output of the group was a [set of community-based requirements to promote the use of semantics for data interoperability, with special focus on agriculture] (https://agrisemantics.org/#agsem_recommendations/).

For details about group participants and activities, see the [Agrisemantics WG page at RDA] (https://www.rd-alliance.org/groups/agrisemantics-wg.html). There, you will also find two intermediate outputs of the group: (1) A report on semantics landscape for agricultural data, and (2) A set of use cases and requirements.

**Comment by catecara** [comment]
Brandon, this is the third issue I meant. It was already created a few days ago but stayed empty until this morning.

**Comment by brandonnodnarb** [comment]
resolved with [this commit](https://github.com/agrisemantics/website/commit/bb2eaadc8ad54b4ebf385bbbda44a36b5cd4c8ee)
