### ISSUE TITLE
new page: Getting involved

### ISSUE THREAD

**Issue by catecara** [agrisemantics/website#20]
You can contribute to improving data interoperability in agriculture through semantics in at least two ways:

1. Give your feedback to the recommendations. You can do that by contributing to the [public discussion on the recommendations](https://github.com/agrisemantics/recommendations/issues)

1. Become and adopter. [Here a list of current adopters](new page in the website).

**Comment by brandonnodnarb** [comment]
This page is directly under Agrisemantics WG, correct?

Is this the exact text you want?

**Comment by catecara** [comment]
Correct. Yes, that's the idea, basic for now. Makes sense?

**Comment by brandonnodnarb** [comment]
done with [this commit](https://github.com/agrisemantics/website/commit/f4b3bc3708794366ea82177ec074f9e40ca26f3f)

**Comment by catecara** [comment]
Text copied below and edited to update the page online.

--- page content

You can contribute to improving data interoperability in agriculture through semantics in at least two ways:

- Give your feedback to the recommendations. You can do that by contributing to the public discussion on the recommendations

- Become and adopter. You qualify as an adopter if you are actively implementing one or more of the recommendations in your initiative/projects/institutions, or if you plan on doing so in the future. YOu also qualify as an adopter if you endorse the general view embodied in the recommendations, even though you are not quite in an implementation phase yet. [Here a list of current adopters](new page in the website).

**Comment by brandonnodnarb** [comment]
I added the text.  I preserved the first link, and fixed the typos :)   If that was not what you intended let me know.

resolved with [this commit](https://github.com/agrisemantics/website/commit/262bf1a1c0ff3b723768e0698f9d071cf3e9b7c7)
