### ISSUE TITLE
New page: Adopters

### ISSUE THREAD

**Issue by catecara** [agrisemantics/website#21]
In this new page, just the following table:

Organisation (project/initiative) | Contact
-- | --
LIRMM (Agroportal / D2KAB) | Clément Jonquet
BC3, Basque Center for Climate Change (Aries) | Ferdinando Villa
Entecra | Giovanni L'Abate
FAO Statistics Division (Caliper proj) | Caterina Caracciolo
GACS | Brandon Whitehead
GO FAIR Food Systems IN | Ben Schaap
GODAN | Ben Schaap
Tor Vergata University (VocBench) | Armando Stellato
Wageningen Data Competence Centre | Willem Jan / Erik / Jacquelijn

**Comment by brandonnodnarb** [comment]
done with [this commit](https://github.com/agrisemantics/website/commit/f4b3bc3708794366ea82177ec074f9e40ca26f3f)

**Comment by catecara** [comment]
ONGOING ---- Attempt to improve the page with a short description of what adoption means in each case.

1. BC3, Basque Center for Climate Change (Aries). Contact: Ferdinando Villa. 
[Aries](http://aries.integratedmodelling.org/) ...

2. Entecra. Contact: Giovanni L'Abate

3. FAO Statistics Division (Caliper proj). Contact: Caterina Caracciolo
[Caliper](http://stats-class.fao.uniroma2.it/caliper/) 

4. GACS. Contact: Brandon Whitehead

5. GO FAIR Food Systems IN | Ben Schaap

6. GODAN | Ben Schaap

7. LIRMM (Agroportal / D2KAB). Contact: Clément Jonquet. The Agroportal is strongly involved in the management of alignments, metadata, repository...

8. Tor Vergata University (VocBench) | Armando Stellato

9. Wageningen Data Competence Centre | Willem Jan / Erik / Jacquelijn

**Comment by saubin78** [comment]
Text for 
- GO FAIR Food Systems Implementation Network supports the implementation of FAIR principles in agri-food sciences, in providing guidelines, tools, methods, etc. with specific efforts towards achieving semantic interoperability. To this end, the Food Systems IN will boost the adoption and implementation of recommendations from existing initiatives, including those produced by Agrisemantics

**Comment by saubin78** [comment]
- The AgroPortal is the community repository for ontologies and thesauri for agriculture and nutrition. It is strongly involved in metadata standardisation and creation and management of alignments. The D2KAB project (2019-2023) drives research on these aspects and aims at developing the agricultural linked data cloud. Contact: Clément Jonquet, LIRMM.

**Comment by saubin78** [comment]
INRA Scientific and Technical Department guides people who develop semantic resources like ontologies and thesauri at INRA. The goal is to make these semantic resources more Findable, Accessible, Interoperable, and Reusable, a key step in making data more FAIR.  https://ist.inra.fr/en/
