### ISSUE TITLE
New adopter for page Adopter

### ISSUE THREAD

**Issue by catecara** [agrisemantics/website#25]
TSCF [url:
https://www.irstea.fr/en/research/research-units/tscf] (Technologies and information systems for agricultural systems) is a data producer, data manager and data consumer. The institute works on the use of sensor data to improve agricultural practices. Sensor data are published as Linked open data, and used within information system in support of human decisions.

**Comment by brandonnodnarb** [comment]
updated with [this commit](https://github.com/agrisemantics/website/commit/f698a1f03a5113df3ccfacfec9938a1e9ec92138).
