### ISSUE TITLE
edit GACShome.md per Imma's request

### ISSUE THREAD

**Issue by semantic-nomad** [agrisemantics/website#29]
The following text has been proposed:
---------------------------------------------------------------------
### Global Agricultural Concept Space (GACS)

The Global Agricultural Concept Space (GACS) is a hub for concepts related to agriculture, in multiple languages, for use in Linked Data. GACS Core is the first of potentially many concept schemes in this larger concept space. The idea for GACS emerged out of discussions at the World Congress of IAALD, the International Association of Agricultural Information Specialists, in July 2013. The Food and Agricultural Organization of the United Nations (FAO), CAB International (CABI), and the National Agricultural Library of the USA (NAL) agreed in October 2013 to explore the feasibility of developing a shared concept scheme by integrating their three thesauri: the AGROVOC Concept Scheme, the CAB Thesaurus (CABT), and NAL Thesaurus (NALT). In the GACS vision, the integration of these three thesauri was the first step towards the realization of a hub that links to and from the concept schemes beyond the initial three, and in multiple language areas. Not actively maintained. Data is from 2016.

#### Browse GACS online

GACS can be [viewed, navigated and searched in a browser](http://browser.agrisemantics.org/gacs/en/) for human readable consumption via the [Skosmos](http://www.skosmos.org/) interface.

#### Download GACS

GACS can be [downloaded as a ZIP file](https://github.com/agrisemantics/website/raw/master/downloads/gacs-core-scheme.zip) holding the main concept scheme for GACS in the Turtle and RDF/XML formats.

#### Contribute
You can provide comments to GACS through the issue tracker on the [gacs-scheme github repository](https://github.com/gacs/gacs-scheme). 

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a>

The Global Agricultural Concept Space (GACS) is licensed by the GACS Working Group under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

**Comment by brandonnodnarb** [comment]
[done](https://github.com/agrisemantics/website/commit/1470b2d4340b28cdfd132f05ef49673486094059)
