### ISSUE TITLE
Why aren't we using the GACS organisation and associated repos for this stuff?

### ISSUE THREAD

**Issue by brandonnodnarb** [agrisemantics/website#5]
Agrisemantics covers many different projects, VEST, AgroPortal, GACS, and many others---at least, in theory.  

Can we keep the GACS stuff in the GACS org and repos here:
https://github.com/gacs 
?

**Comment by tombaker** [comment]
On Thu, Dec 06, 2018 at 08:17:43AM -0800, brandon wrote:
> Agrisemantics covers many different projects, VEST, AgroPortal, GACS, and many others---at least, in theory.  
> 
> Can we keep the GACS stuff in the GACS org and repos here:
> https://github.com/gacs 

Fine with me.  I believe Github is good about redirecting to new
repositories.  The GACS URIs are under id.agrisemantics.org, which
shouldn't change, and if possible, there should be a splash page for
GACS at each address that people are likely to have bookmarked.

**Comment by brandonnodnarb** [comment]
discuss GACS at https://github.com/gacs/gacs-scheme
or other repos on https://github.com/gacs/
