### ISSUE TITLE
GACS Skosmos browser still says "GACS Beta"

### ISSUE THREAD

**Issue by tombaker** [agrisemantics/website#9]
The [GACS Skosmos browser](http://browser.agrisemantics.org/gacs/en/) still calls itself "GACS Beta" and "Global Agricultural Concept Scheme Core" and the description reads: "The Global Agricultural Concept Scheme (GACS) is a hub for concepts...".

We may need to clarify first whether Skosmos will be able to display multiple concept schemes, as this would determine how the Skosmos instance describes itself.

**Comment by brandonnodnarb** [comment]
this is in progress.

**Comment by brandonnodnarb** [comment]
Email sent to Andrea at Tor Vergata.

**Comment by brandonnodnarb** [comment]
Fixed.  @tombaker check out the browser pages when you are back.

**Comment by tombaker** [comment]
This is much better, however I am reopening this issue because I think the presentation can be improved.  The text currently says:

```
TITLE    GACS Core
         Global Agricultural Concept Space core concepts
         Global Agricultural Concept Space Core
```

I suggest dropping the line with `Space Core`.
 
```
The Global Agricultural Concept Space (GACS) is a hub for concepts related to agriculture, in multiple languages, for use in LinkedData. The idea for GACS... is but the first step towards the realization of a hub that links to and from the concept schemes beyond the initial three, and in multiple language areas.
```

I suggest that the first sentence above be followed by a second sentence:
```
GACS Core is the first of potentially many concept schemes in this larger concept space.
```

**Comment by brandonnodnarb** [comment]
Done.  There appears to be two sections of metadata with two separate `dc:title` tags for some reason.   

I'll email Andrea.

**Comment by brandonnodnarb** [comment]
Andrea just emailed --- the new gacs ttl file has been uploaded and is now live.

see: http://browser.agrisemantics.org/gacs/en/
